// src/routes/pulls.tsx
import { MetaProvider, Title } from "@solidjs/meta";
import { Show } from "solid-js";
import { getSearchPullRequests } from "~/api/getSearchPullRequests";
import { Flex } from "~/components/Flex/Flex";
import { PullRequestList } from "~/components/PullRequestList/PullRequestList";

export default function PullsPage() {
  const myPullRequestsQuery = getSearchPullRequests({
    q: `state:open author:@me is:pull-request`,
  });

  const myReviewPullRequestsQuery = getSearchPullRequests({
    q: `state:open is:pull-request review-requested:@me`,
  });

  return (
    <Flex gap={16} direction="column">
      <Title>Pull requests</Title>
      <h1>Pull requests</h1>

      <Show when={!myPullRequestsQuery.isLoading}>
        <PullRequestList
          title={`My pull requests (${myPullRequestsQuery.data?.data.total_count})`}
          pullRequests={myPullRequestsQuery.data?.data.items ?? []}
          isError={myPullRequestsQuery.isError}
          noRequestsMessage="👌 You don't have any outstanding pull requests"
        />
      </Show>

      <Show when={!myReviewPullRequestsQuery.isLoading}>
        <PullRequestList
          title={`My reviews (${myReviewPullRequestsQuery.data?.data.total_count})`}
          pullRequests={myReviewPullRequestsQuery.data?.data.items ?? []}
          isError={myReviewPullRequestsQuery.isError}
          noRequestsMessage="✅ You're all caught up with code reviews!"
        />
      </Show>
    </Flex>
  );
}

// src/routes/pulls/+page.svelte
<script lang="ts">
	import Flex from '$lib/components/Flex.svelte';
	import PullRequestList from '$lib/components/PullRequestList.svelte';

	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	function handleKeyUp(event: KeyboardEvent) {
		const focusedItem = document.activeElement;
		const allFocusableListItems = document.querySelectorAll(
			'[data-keyboard-focusable]',
		);
		const focusedItemIndex = focusedItem
			? Array.from(allFocusableListItems).indexOf(focusedItem)
			: -1;

		if (event.key === 'ArrowUp' || event.key === 'k') {
			if (focusedItemIndex === -1) return;

			allFocusableListItems[Math.max(0, focusedItemIndex - 1)].focus();

			return;
		}

		if (event.key === 'ArrowDown' || event.key === 'j') {
			allFocusableListItems[
				Math.min(allFocusableListItems.length - 1, focusedItemIndex + 1)
			].focus();
			return;
		}
	}
</script>

<svelte:window onkeyup={handleKeyUp} />

<svelte:head>
	<title>Pull requests</title>
</svelte:head>

<Flex gap={16} direction="column">
	<h1>Pull requests</h1>

	<PullRequestList
		title={`My pull requests (${data.myPullRequests.length})`}
		pullRequests={data.myPullRequests}
		isError={data.isError}
		noRequestsMessage="👌 You don't have any outstanding pull requests"
	/>

	<PullRequestList
		title={`My reviews (${data.myReviewPullRequests.length})`}
		pullRequests={data.myReviewPullRequests}
		isError={data.isError}
		noRequestsMessage="✅ You're all caught up with code reviews!"
	/>
</Flex>
