// src/lib/components/PullRequestDiscussion.svelte
<script lang="ts">
	import type { ConsolidatedComment } from '$lib/types';
	import Flex from './Flex.svelte';
	import PullRequestComment from './PullRequestComment.svelte';
	import Text from './Text.svelte';

	export type PullRequestDiscussion = {
		comments: ConsolidatedComment[];
	};

	const { comments }: PullRequestDiscussion = $props();
</script>

<Flex direction="column" gap={16}>
	{#if comments.length === 0}
		<Text>🥱 No discussion yet</Text>
	{:else}
		{#each comments as comment}
			<PullRequestComment {comment} />
		{/each}
	{/if}
</Flex>

// src/components/PullRequestDiscussion/PullRequestDiscussion.tsx
import { For, Show } from "solid-js";
import { Flex } from "../Flex/Flex";
import { Text } from "../Text/Text";
import { ConsolidatedComment } from "~/types/local";
import { PullRequestComment } from "../PullRequestComment/PullRequestComment";

export type PullRequestDiscussionProps = {
  comments: ConsolidatedComment[];
};

export function PullRequestDiscussion(props: PullRequestDiscussionProps) {
  return (
    <Flex direction="column" gap={16}>
      <Show
        when={props.comments.length !== 0}
        fallback={<Text>🥱 No discussion yet</Text>}
      >
        <For each={props.comments}>
          {(comment) => <PullRequestComment comment={comment} />}
        </For>
      </Show>
    </Flex>
  );
}
