// src/lib/components/PullRequestComment.svelte
<script lang="ts">
	import type { ConsolidatedComment } from '$lib/types';
	import { formatDistance } from 'date-fns/fp';
	import Box from './Box.svelte';
	import BoxBody from './BoxBody.svelte';
	import BoxTitle from './BoxTitle.svelte';
	import Flex from './Flex.svelte';
	import ReviewStateIcon from './ReviewStateIcon.svelte';
	import Text from './Text.svelte';
	import PullRequestComment from './PullRequestComment.svelte';
	import HighlightedCode from './HighlightedCode.svelte';
	import { getFileExtension } from '$lib/utils/getFileExtension';
	import UserSubmittedText from './UserSubmittedText.svelte';

	export type PullRequestCommentProps = {
		comment: ConsolidatedComment;
	};

	const { comment }: PullRequestCommentProps = $props();
</script>

<Box>
	<BoxTitle>
		<Flex gap={4} align="center">
			<ReviewStateIcon state={comment.state} />
			<Text size="p2">{comment.author.login} {comment.state}</Text>
			<Text variant="subtle" size="p2">
				{comment.createdAt && formatDistance(comment.createdAt, new Date())} ago
			</Text>
		</Flex>
	</BoxTitle>
	{#if comment.body || comment.replies || comment.diff}
		<BoxBody>
			{#if comment.diff}
				<div>
					{comment.diff.path}
				</div>
				<HighlightedCode
					code={comment.diff.diff}
					extension={getFileExtension(comment.diff.path)}
				/>
			{/if}

			{#if comment.body}
				<UserSubmittedText text={comment.body} />
			{/if}

			{#if comment.replies}
				{#each comment.replies as reply}
					<PullRequestComment comment={reply} />
				{/each}
			{/if}
		</BoxBody>
	{/if}
</Box>

// src/components/PullRequestComment/PullRequestComment.tsx
import { ConsolidatedComment } from "~/types/local";
import { Box } from "../Box/Box";
import { BoxTitle } from "../BoxTitle/BoxTitle";
import { Flex } from "../Flex/Flex";
import { ReviewStateIcon } from "../ReviewStateIcon/ReviewStateIcon";
import { Text } from "../Text/Text";
import { formatDistance } from "date-fns";
import { For, Show } from "solid-js";
import { BoxBody } from "../BoxBody/BoxBody";
import { UserSubmittedText } from "../UserSubmittedText/UserSubmittedText";
import { getFileExtension } from "~/utils/getFileExtension";
import { HighlightedCode } from "../HighlightedCode/HighlightedCode";

export type PullRequestCommentProps = {
  comment: ConsolidatedComment;
};

export function PullRequestComment(props: PullRequestCommentProps) {
  return (
    <Box>
      <BoxTitle>
        <Flex gap={4} align="center">
          <ReviewStateIcon state={props.comment.state} />
          <Text size="p2">
            {props.comment.author.login} {props.comment.state}
          </Text>
          <Text variant="subtle" size="p2">
            {props.comment.createdAt &&
              formatDistance(props.comment.createdAt, new Date())}{" "}
            ago
          </Text>
        </Flex>
      </BoxTitle>
      <Show
        when={props.comment.body || props.comment.replies || props.comment.diff}
      >
        <BoxBody>
          <Show when={props.comment.diff}>
            <div>{props.comment.diff!.path}</div>
            <HighlightedCode
              code={props.comment.diff!.diff}
              extension={getFileExtension(props.comment.diff!.path)}
            />
          </Show>

          <Show when={props.comment.body}>
            <UserSubmittedText text={props.comment.body} />
          </Show>

          <Show when={props.comment.replies}>
            <For each={props.comment.replies}>
              {(reply) => <PullRequestComment comment={reply} />}
            </For>
          </Show>
        </BoxBody>
      </Show>
    </Box>
  );
}
