// src/components/CheckRunsList/CheckRunsList.tsx
import { For, Show } from "solid-js";
import { CheckRun } from "~/types/api";
import { sortCheckRuns } from "~/utils/sortCheckRuns";
import { Flex } from "../Flex/Flex";
import { CheckRunsIcon } from "../CheckRunsIcon/CheckRunsIcon";

import * as styles from "./CheckRunsList.css";

export type CheckRunsListProps = {
  checkRuns?: CheckRun[];
};

export function CheckRunsList(props: CheckRunsListProps) {
  const sortedRuns = sortCheckRuns(props.checkRuns ?? []);

  return (
    <ul class={styles.ul}>
      <For each={sortedRuns}>
        {(check) => (
          <li class={styles.li}>
            <Show
              when={check.details_url !== "undefined"}
              fallback={
                <Flex gap={8}>
                  <CheckRunsIcon
                    status={check.status}
                    conclusion={check.conclusion}
                  />
                  <span>{check.name}</span>
                </Flex>
              }
            >
              <a href={check.details_url!} target="_blank">
                <Flex gap={8}>
                  <CheckRunsIcon
                    status={check.status}
                    conclusion={check.conclusion}
                  />
                  <span>{check.name}</span>
                </Flex>
              </a>
            </Show>
          </li>
        )}
      </For>
    </ul>
  );
}

// src/lib/components/CheckRunsList.svelte
<script lang="ts">
	import type { CheckRun } from '$lib/types';
	import { sortCheckRuns } from '$lib/utils/sortCheckRuns';
	import CheckRunIcon from './CheckRunIcon.svelte';
	import Flex from './Flex.svelte';

	type CheckRunsListProps = {
		checkRuns: CheckRun[];
	};

	const { checkRuns }: CheckRunsListProps = $props();

	const sortedRuns = sortCheckRuns(checkRuns);
</script>

<ul>
	{#each sortedRuns as check}
		<li>
			<a href={check.details_url} target="_blank">
				<Flex gap={8}
					><CheckRunIcon
						status={check.status}
						conclusion={check.conclusion}
					/><span>{check.name}</span></Flex
				></a
			>
		</li>
	{/each}
</ul>

<style>
	ul {
		list-style: none;
		padding: 0;
		margin-block: 0;
	}

	li:not(:last-child) {
		margin-block-end: 0.25rem;
	}
</style>
