// src/components/CheckRunsSummary/CheckRunsSummary.tsx
import { CheckRun } from "~/types/api";
import { Flex } from "../Flex/Flex";
import { createEffect, createMemo, For } from "solid-js";
import { sortCheckRuns } from "~/utils/sortCheckRuns";
import { CheckRunsIcon } from "../CheckRunsIcon/CheckRunsIcon";

import * as styles from "./CheckRunsSummary.css";

export type CheckRunsSummaryProps = {
  checkRuns?: CheckRun[];
};

export function CheckRunsSummary(props: CheckRunsSummaryProps) {
  const groupedRuns = createMemo(() => {
    const sortedRuns = sortCheckRuns(props.checkRuns ?? []);

    return sortedRuns.reduce((acc, run) => {
      const key = `${run.status}-${run.conclusion}`;
      if (!acc.has(key)) {
        acc.set(key, []);
      }

      acc.get(key)!.push(run);

      return acc;
    }, new Map<string, CheckRun[]>());
  });

  return (
    <ul class={styles.checkRunsList}>
      <For each={Array.from(groupedRuns().values())}>
        {(runs) => (
          <li>
            <Flex gap={4} align="center">
              <CheckRunsIcon
                status={runs[0].status}
                conclusion={runs[0].conclusion}
              />
              <span>{runs.length}</span>
            </Flex>
          </li>
        )}
      </For>
    </ul>
  );
}

// src/lib/components/CheckRunsSummary.svelte
<script lang="ts">
	import type { CheckRun } from '$lib/types';
	import { sortCheckRuns } from '$lib/utils/sortCheckRuns';
	import CheckRunIcon from './CheckRunIcon.svelte';
	import Flex from './Flex.svelte';

	type CheckRunsListProps = {
		checkRuns: CheckRun[];
	};

	const { checkRuns }: CheckRunsListProps = $props();

	const sortedRuns = sortCheckRuns(checkRuns);
	const groupedRuns = sortedRuns.reduce((acc, run) => {
		const key = `${run.status}-${run.conclusion}`;
		if (!acc.has(key)) {
			acc.set(key, []);
		}

		acc.get(key)!.push(run);

		return acc;
	}, new Map<string, CheckRun[]>());
</script>

<ul>
	{#each groupedRuns.values() as runs}
		<li>
			<Flex gap={4} align="center"
				><CheckRunIcon
					status={runs[0].status}
					conclusion={runs[0].conclusion}
				/><span>{runs.length}</span></Flex
			>
		</li>
	{/each}
</ul>

<style>
	ul {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		list-style: none;
		padding: 0;
		margin-block: 0;
	}
</style>
